### PR TITLE
Make the whisper to function not case sensitive

### PR DESCRIPTION
**Pull request by Pocketpac**
Convert both the username and the sql query usernames to lowercase to make it not be case sensitive

### CODE REVIEW

**Comment by SReject** [comment]
With commit b06ea84a9c1e28608b01a253e7bff2f515f72700 if the passed-in `WhisperTo`(`arg[0]`) variable is not a string, the `.toLowerCase()` will raise an error.

**Comment by Pocketpac** [comment]
U raise good points, I sheall relook at this

**Comment by ProbablePrime** [comment]
You typically don't need to close a request. Just add [WIP] to the title :)

**Comment by MattJustMatt** [comment]
We no longer support [WIP] PRs. In order to keep things running smoothly a PR needs to be a fully complete and thought out implementation! @ProbablePrime

**Comment by ProbablePrime** [comment]
Oh Fair enough :D

**Comment by ttaylorr** [comment]
Closed in #34

**Pull request closed without merging**
