### PR TITLE
Include the full sent message in the callback

### PR DESCRIPTION
**Pull request by connor4312**
We include it for whispers, it makes logic easier if we just call back with the full message whenever a message is sent.

### CODE REVIEW

**Comment by JamyDev** [comment]
Why did you remove the check for uuid? It should still be sent down so I suggest testing for it too.

**Comment by connor4312** [comment]
The ID is actually sent down as an `id` property of the message object. That's one reason I removed the uuid thing; we ended up having to do `response.id || response.uuid` if we wanted a unified interface to handle whispers

**Comment by JamyDev** [comment]
Well thin I think we should make it consistently send down either `id` or `uuid`. But that's sorta out of the scope of this PR since that might be a breaking change for whispers.

**Comment by connor4312** [comment]
Yea, this does make it consistent 😄

**Comment by connor4312** [comment]
Previous to their PR we were sending down a `uuid` property for chat messages (not that this change was not deployed yet). Now we respond with the entire generated ChatMessage which includes an `id`, in the same way that we do for whisper.

**Comment by JamyDev** [comment]
I think you misunderstood my comment, I was wondering why you removed the test that checked if it sends down a correct uuid as the `id` property, or at the very least test if `id` is even populated.

**Comment by connor4312** [comment]
Ah, sure. I can re-add tests for that

**Comment by connor4312** [comment]
Added in 536fad2

**Comment by JamyDev** [comment]
LGTM

**Comment by ttaylorr** [comment]
👍

**Pull request merged**
