### PR TITLE
Force the message to be not blank or undef/null

### PR DESCRIPTION
**Pull request by connor4312**
Fixes https://github.com/WatchBeam/chat/issues/58

### CODE REVIEW

**Comment by connor4312** [comment]
Test will fail because this branch is lacking 21aab58

**Comment by ttaylorr** [comment]
Works for me :+1:

**Comment by JamyDev** [comment]
LGTM

**Comment by artdude543** [comment]
Would it be an idea to add an additional check for trimming and checking the length? I've seen a few times empty messages still being pipped to the socket. Some are just spaces and others are plain empty which is odd cos this check should prevent that.

**Comment by MattJustMatt** [comment]
Can you show us some examples of this @artdude543 

As many cases as possible will help us to expedite this

**Pull request merged**
