### PR TITLE
Update start.js

### PR DESCRIPTION
**Pull request by ChilliByte**
Added "@" functionality to giveaway bot.

### CODE REVIEW

**Comment by MCProhosting-Matt** [comment]
Thanks! Please update the unit tests as well. :)

**Comment by JamyDev** [comment]
Unit tests are located here ;) https://github.com/WatchBeam/widgets/blob/master/giveaway/test/chat.test.js

**Comment by ChilliByte** [comment]
I'm not sure what I'm doing there, I'm not familiar with the framework you're using

**Comment by ChilliByte** [comment]
Is it line 14 that I should modify?

**Comment by JamyDev** [comment]
Yeah

**Comment by ChilliByte** [comment]
Like that? Sorry, not too familiar with Git

**Comment by JamyDev** [comment]
yup that's good, let's just wait what travis says and we might be good to go ;)

**Pull request merged**
