### PR TITLE
Remove @ from the whisper target.

### PR DESCRIPTION
**Pull request by artdude543**
Fixes issue with people using the autocomplete feature which appends @ to the username.

### CODE REVIEW

**Comment by artdude543** [comment]
This is also a bug with the `/mod /ban /unban` commands.

**Comment by ttaylorr** [comment]
Thanks for this! Perhaps we could find a more generic solution to cover all four cases?

**Comment by artdude543** [comment]
Yeah might be more ideal but the widgets does not have the other commands here to fix. So unsure to how the fix could be applied to the others.

**Comment by ttaylorr** [comment]
Ah, that's right -- my mistake. Passing this one on to @connor4312.

**Comment by artdude543** [comment]
Want me to also PR a fix for being able to whisper yourself also? Seems kind of odd that you can do that.

**Comment by connor4312** [comment]
Thanks for the contribution, but I want to put this in as a fix on our frontend rather than one on the chat server. The chat server shouldn't care where messages are coming from (beam.pro, a robot, or even another widget). This is a fix to support specific behaviour on one medium (the beam.pro frontend), so I believe it should happen there.

A fix for whispering to yourself would be appreciated :smile:.

**Comment by MCProhosting-Matt** [comment]
Quick note, we have an internal issue to get this done as well. <3

**Pull request closed without merging**
