### PR TITLE
Giving GiveawayBot An Avatar

### PR DESCRIPTION
**Pull request by MrAdder**
Giveaway Bot has the same avatar as BeamBot and should no longer 404

### CODE REVIEW

**Comment by MrAdder** [comment]
Compiles fine locally and can be tested with no errors

**Comment by JamyDev** [comment]
Remove the build numbers pls

**Comment by MrAdder** [comment]
Done

**Comment by connor4312** [comment]
Also: please make the URL absolute! If chat is embedded on other sites, they'd have to hard-code in logic like `if (str.startsWith('/')) str = 'https://beam.pro/' + str`

**Comment by MrAdder** [comment]
Done

**Comment by connor4312** [comment]
Awesome, thanks :smile:

**Pull request merged**
