### PR TITLE
Include a 'text' property in text messages

### PR DESCRIPTION
**Pull request by connor4312**
This modifies the message widget to include a `text` property in text-type messages. `data` is kept there for backwards compatibility, but consistently including text makes processing easier.

### CODE REVIEW

**Comment by connor4312** [comment]
No idea why Travis is failing, it works locally on a fresh install :/

**Comment by SimonSchick** [comment]
I am experiencing the build failure locally as well, not just travis.

**Comment by SimonSchick** [comment]
The problem is that node silently swallows the error thrown in the `timeout` callback.

Here is the error:

```
111 passing (2s)
  1 failing

  1) timeout method allows good calls:
     expected publishAsync to have been called with arguments chat:1337:UserTimeout, {"user":42,"until":"Wed Dec 31 1969 16:00:10 GMT-0800 (PST)"}
    publishAsync(chat:1337:UserTimeout, {"user":42,"until":"Thu Jan 01 1970 01:00:10 GMT+0100 (CET)"}) => [object Promise] at /Users/simonschick/Documents/projects/beam/widgets/timeout/chat/timeout.js:163:29
  AssertionError: expected publishAsync to have been called with arguments chat:1337:UserTimeout, {"user":42,"until":"Wed Dec 31 1969 16:00:10 GMT-0800 (PST)"}
      publishAsync(chat:1337:UserTimeout, {"user":42,"until":"Thu Jan 01 1970 01:00:10 GMT+0100 (CET)"}) => [object Promise] at timeout/chat/timeout.js:163:29
      at timeout/test/chat.test.js:167:66
      at tryCatcher (node_modules/bluebird/js/main/util.js:26:23)
      at Promise.successAdapter (node_modules/bluebird/js/main/nodeify.js:23:30)
      at bound (domain.js:287:14)
      at Promise.runBound (domain.js:300:12)
      at Promise._settlePromiseAt (node_modules/bluebird/js/main/promise.js:579:21)
      at Promise._settlePromises (node_modules/bluebird/js/main/promise.js:697:14)
      at Async._drainQueue (node_modules/bluebird/js/main/async.js:123:16)
      at Async._drainQueues (node_modules/bluebird/js/main/async.js:133:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/main/async.js:15:14)
```

**Comment by SimonSchick** [comment]
I'd also recommend _not_ using the default date format but rather use `toJSON()` which will yield a timestamp without timezone information.

**Pull request merged**
